// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jinzgjgbghalnkzevhjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppbnpnamdiZ2hhbG5remV2aGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTExOTcsImV4cCI6MjA2NzU2NzE5N30.aJqy6_9IiB3rB7HU7tNA5-S--4i59h2AhwwOhhnJNUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});